services:
  weather-app:
    env_file: .env
    build:
      context: ./weather-app
    container_name: ${WEATHER_APP_NAME:-weather-app}
    ports:
      - "${WEATHER_PORT:-3001}:${WEATHER_PORT:-3001}"
    environment:
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-mariadb}
      - TZ=${TIMEZONE:-America/Chicago}
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    volumes:
      - ./weather-app:/app
    networks:
      - app-network
    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:${WEATHER_PORT:-3001}" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
