services:
  express-app:
    build:
      context: .
    container_name: express-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=192.168.2.2
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mariadb
    depends_on:
      - mariadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.2.2:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306" # Exposes MySQL on the network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf # Add this line to load the config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "192.168.2.2" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb_data:
