services:
  express-app:
    env_file: .env
    build:
      context: .
    container_name: ${EXPRESS_APP_NAME:-express-app}
    ports:
      - "${EXPRESS_PORT:-3000}:${EXPRESS_PORT:-3000}"
    environment:
      - DB_HOST=${DB_HOST:-127.0.0.1}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-mariadb}
      - TZ=${TIMEZONE:-America/Chicago}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - .:/app
    tty: true
    privileged: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:${EXPRESS_PORT:-3000}" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:
