services:
  # express-app:
  #   env_file: .env
  #   build:
  #     context: .
  #   container_name: express-app
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - DB_HOST=127.0.0.1
  #     - DB_USER=root
  #     - DB_PASSWORD=password
  #     - DB_NAME=mariadb
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - .:/app
  #   devices:
  #     - "/dev/us.usbmodem1101:/dev/us.usbmodem1101"
  #   tty: true
  #   privileged: true
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://127.0.0.1:5001" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306" # Exposes MySQL on the network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf # Add this line to load the config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb_data:
